# Como trabalhar no R
  
Se voce ja tem uma nocao de R, mas ainda sente dificuldade de organizar seu fluxo de trabalho, esse capitulo eh pra voce! Utilizaremos tecnicas de ciencia de dados e repositorios como o github para tornar o trabalho no R prazeroso e eficiente!
  
Se voce possuir um banco de dados para analizar a quantidade de parasitas de aves da mata atlantica, ou o comportamento sexual de caranguejos chama-mares (ou seja la qual for o seu estudo), aproveite para utiliza-lo aqui nesse capitulo. Caso voce ainda nao possua seu banco de dados, trabalharemos com algum banco de dados nativo do R. Optei por utilizar o banco de dados "iris", mas sinta-se a vontade para utilizar qualquer outro.

Primeiro vamos exportar o banco de dados iris para que possamos simularmos todo o precesso desde a sua importacao. Para isso, iremos carregar o banco de dados iris utilizando a funcao *data()*, e utilizaremos a funcao *write.csv()* para exportar, no formato csv, a planilha "iris" para o computador. Deixe essa planilha salva em algum lugar no computador e finja que ela eh sua, mais para frente iremos utiliza-la.

```r

#Carregando pacote de dados iris
data(iris)

#Salvando (exportando) iris no computador
write.csv(x = iris,            #nome do banco de dados do R
          file = "iris.csv",   #nome do banco de dados salvo no computador
          row.names = FALSE)   #Mostrar o nome das linhas na planilha salva utilizando TRUE ou nao utilizando FALSE.
```
  
Para entender a funcao *write.csv()* modifique alguns argumentos:

  - Substitua: file = "iris.csv" por file = "planilha_do_R.csv".
  - Substitua: row.names = FALSE, por row.names = TRUE.
  
Por padrao, iremos utilizar sempre row.names = FALSE.
  
## Criando um projeto de R
  
Imaginemos que precisamos analisar um banco de dados de algum projeto. O primeiro passo eh criar um projeto de R, para isso voce vai no canto superior direito e clicar em "project (none)" > new project.

## Git e GitHub
  
## 


